const ExperienceDb = [
        { 
            id: -1,
            lang: "en",
            title: "fdp (Financière des professionnnels)",
            subtitle: "Feb. 2021 to Present",
            leftTitle: "Webmaster, administrator of web platforms and CSS/jQuery/HTML5 Developer. My responsibilities include:",
            leftList: "<li>Management of the corporate website and client zone</li><li>Primary contact with IT department for all web-related projects and liaising with vendors as required</li><li>Providing website metrics</li><li>Creating forms with online payments and connected to local databases</li><li>Developing custom Microsites</li>",
            rightTitle: "Some notable projects related to this position:",
            rightList: "<li><strong><a href='https://www.fdpgp.ca/hhs/' target='_blank' rel='noopener noreferrer'>HHS</a></strong> & <strong><a href='https://www.fdpgp.ca/bernier-drolet/'>Bernier-Drolet</a> teams' microsites</strong><br />Based on a design produced by our graphic designers, I've coded these 2 responsive microsites 'by hand' using HTML, CSS & JavaScript.</li><li>Graphical revamp of our main website at <a href='https://www.fdpgp.ca'>www.fdpgp.ca</a></li>"
        },
        { 
            id: 0,
            lang: "fr",
            title: "fdp (Financière des professionnnels)",
            subtitle: "Fév. 2021 à présent",
            leftTitle: "Webmestre, administrateur des plateformes web et développeur CSS/jQuery/HTML5. Mes responsabilitées incluent:",
            leftList: "<li>Maintien des sites corpo et de la zone client</li><li>Premier contact avec le département des TIs pour tou projet relié au web et liaison avec les fournisseurs.</li><li>Analyse des données métriques</li><li>Création de formulaires avec paiement en ligne et connexion à bases de données internes</li><li>Développement de micro-sites</li>",
            rightTitle: "Quelques projets à souligner en lien avec ce poste :",
            rightList: "<li><strong>Èquipes <a href='https://www.fdpgp.ca/hhs/' target='_blank' rel='noopener noreferrer'>HHS</a></strong> et <strong><a href='https://www.fdpgp.ca/bernier-drolet/'>Bernier-Drolet</a></strong><br />Basé sur un design produit par nos graphistes, j'ai entièrement créé ces 2 sites responsive 'à bras' avec les technos HTML, CSS et JavaScript.</li><li>Redesign graphique du site web principal à <a href='https://www.fdpgp.ca'>www.fdpgp.ca</a></li>"
        },
        { 
            id: 1,
            lang: "en",
            title: "McCarthy Tétrault",
            subtitle: "Sep. 2014 to June 2020",
            leftTitle: "Webmaster, coordinator and CSS/jQuery/HTML5 Developer. My responsibilities included:",
            leftList: "<li>Maintaining the firm’s corporate and recruitment websites (production and design)</li><li>Primary contact and project manager for internal website requests</li><li>Primary contact with IT department for all web-related projects and liaising with vendors as required</li><li>Support for design and layout of electronic external (clients) and internal communications</li><li>Management of the firm-wide electronic event invitations process</li><li>Providing website metrics</li><li>Active participation in social media/online/technology related products</li>",
            rightTitle: "Some notable projects related to this position:",
            rightList: "<li><strong><a href='https://www.mtversion.ca' target='_blank' rel='noopener noreferrer'>MT Version</a></strong> and <strong><a href='https://www.mtventures.ca'>MT Ventures</a></strong><br />Based on a design produced by a collaboration of my input and the design team, I have built this website's content from scratch.</li><li><strong><a href='https://marcomm.mccarthy.ca/marcomm/cybersecurity/index.html' target='_blank' rel='noopener noreferrer'>CyberSecurity Guide</a></strong><br />Small one pager website I developed using Bootstrap, based on an existing PDF document. I tried to retain the look and feel of the PDF to apply it to the web.</li><li><strong><a href='https://marcomm.mccarthy.ca/marcomm/projects_map/' target='_blank' rel='noopener noreferrer'>Global Projects Map</a></strong><br />Very simple HTML5 website based on JSON with a Google Spreadsheet as its main data source</li>"
        },
        { 
            id: 2,
            lang: "fr",
            title: "McCarthy Tétrault",
            subtitle: "Sep. 2014 à juin 2020",
            leftTitle: "Webmestre, coordinateur et développeur CSS/jQuery/HTML5. Mes responsabilitées incluaient:",
            leftList: "<li>Maintien des sites corpo et de recrutement de la firme (production et design)</li><li>Premier contact et gestionnaire de projet pour requêtes à l'interne</li><li>Premier contact avec le département des TIs pour tou projet relié au web et liaison avec les fournisseurs.</li><li>Support du design et mise en page des communiqués par courriel (clients) et communications internes</li><li>Gestion du processus des invitations électroniques</li><li>Analyse des données métriques</li><li>Participation active dans les réseaux sociaux et autres technologies émergeantes.</li>",
            rightTitle: "Quelques projets à souligner en lien avec ce poste :",
            rightList: "<li><strong><a href='https://www.mtversion.ca' target='_blank' rel='noopener noreferrer'>MT Version</a></strong> et <strong><a href='https://www.mtventures.ca'>MT Ventures</a></strong><br />Basé sur un design produit en collaboration de mon input et du design team, j'ai entièrement créé ces 2 sites 'à bras'.</li><li><strong><a href='https://marcomm.mccarthy.ca/marcomm/cybersecurity/index-fr.html' target='_blank' rel='noopener noreferrer'>Guide de cybersécurité</a></strong><br />Petit site animé que j'ai développé à l'aide de Bootstrap, basé sur un document PDF existant. J'ai tenté de garder le même 'look and feel' exact du PDF mais en y apportant des éléments web.</li><li><strong><a href='https://marcomm.mccarthy.ca/marcomm/projects_map/fr/index.html' target='_blank' rel='noopener noreferrer'>Carte des projets</a></strong><br />Petit site en HTML5 website basé sur Google Maps ainsi qu'une base de données Google Spreadsheet accessible en JSON. </li>"
        },
        {
            id: 3,
            lang: "en",
            title: "Softvoyage",
            subtitle: "Nov. 2012 to Mar. 2014",
            leftTitle: "Web Designer and CSS/jQuery/HTML5 Developer. Worked on general graphic design as well as HTML5 development and UI design, with a special focus on mobile devices and responsive design. More recently started developing in-house web applications using PHP and MySQL/MariaDB. Most of the work was done on a Mac OS X client machine with code running on Linux servers (CentOS, RHLE).",
            leftList: "",
            rightTitle: "Some notable projects related to this position:",
            rightList: "<li><strong>The SIREV travel search engine</strong> (<a href='https://www.sirev.com/' target='_blank' rel='noopener noreferrer'>sirev.com</a>)<br />My main task at Softvoyage was to convert their SIREV search engine from a desktop-only website into a responsive one that would work on mobile devices. I used Bootstrap as a base to code and design the Front-End.</li><li><strong>Main Softvoyage Website</strong> (<a href='https://www.softvoyage.com' target='_blank' rel='noopener noreferrer'>www.softvoyage.com</a>)<br />Based on a provided design, I have mostly built this Wordpress website's content and functionalities</li><li><strong>HTML5 Holidays Greetings card</strong> (<a href='https://holidays.softvoyage.com' target='_blank' rel='noopener noreferrer'>holidays.softvoyage.com</a>)<br />Greetings card built entirely in HTML5/CSS3 and jQuery.</li><li><strong>AvenirMD</strong> (<a href='https://www.avenirmd.com' target='_blank' rel='noopener noreferrer'>www.avenirmd.com</a>)<br />Side project I worked on, built the entire Wordpress website based on a template that I heavily modified using PHP and jQuery.</li>"
        },
        {
            id: 4,
            lang: "fr",
            title: "Softvoyage",
            subtitle: "Nov. 2012 à mars 2014",
            leftTitle: "Designer web et développeur CSS/jQuery/HTML5. Travaillé sur des projets de design graphiques ainsi qu'à du développement et design UI, avec un focus particulier sur les appareils mobiles et le 'responsive design'. Aussi travaillé sur des projets plus backend avec PHP et MySQL, et WordPress. J'ai travaillé surtout sur Mac OS X mais en connection constante sur des serveurs Linux pour le code (CentOS, RHLE).",
            leftList: "",
            rightTitle: "Quelques projets à souligner en lien avec ce poste :",
            rightList: "<li><strong>L'engin de recherche de voyage SIREV</strong> (<a href='https://www.sirev.com/' target='_blank' rel='noopener noreferrer'>sirev.com</a>)<br />Mon pricincipal mandat à Softvoyage fut de convertir leur engin de recherche pour agences de voyages SIREV d'un site web pour 'desktop' seulement en une application mobile 'responsive' qui s'adapte aux plus petits appareils mobiles (iPhone, iPad, Android, etc.). J'ai utilisé Bootstrap comme base pour coder tout le front-end.</li><li><strong>Le site web principal de Softvoyage</strong> (<a href='https://www.softvoyage.com' target='_blank' rel='noopener noreferrer'>www.softvoyage.com</a>)<br />Basé sur un design pré-établi, j'ai bâti ce site Wordpress, autant le contenu que les fonctionnalitées en PHP et jQuery.</li><li><strong>Carte de souhaits interactive</strong> (<a href='https://holidays.softvoyage.com' target='_blank' rel='noopener noreferrer'>holidays.softvoyage.com</a>)<br />Carte de souhaits entièrement bâtie en HTML5/CSS3 et jQuery. Pas de Flash!</li><li><strong>AvenirMD</strong> (<a href='https://www.avenirmd.com' target='_blank' rel='noopener noreferrer'>www.avenirmd.com</a>)<br />Projet parallèle que j'ai bâti entièrement, à partir d'un template que j'ai énormément modifié et amélioré à l'aide de PHP and jQuery.</li>"
        },
        {
            id: 5,
            lang: "en",
            title: "Shanghai United International School",
            subtitle: "2004-2012",
            leftTitle: "Cross-campus coordinator for a series of primary schools in Shanghai (Xiehe Education Group). I acted as an advisor, system administrator, facilitator and teacher. My tasks included managing the IT infrastructures across campuses and administrating the school’s web servers, databases, e-mail, FTP, Administration desk, etc. I have also deployed a Learning Management System (Moodle) and developed several web apps and databases for administrative functions (PHP+MySQL). On top of that, I was also providing technical support and training to teachers, as well as teaching ICT to primary and secondary school students. I followed the IB curriculum program as well as IPC and the English National Curriculum. You can consult some of my IB workshops attendance certificates by <a href='https://www.dropbox.com/sh/hh6ixhzowx8kle7/EMoi0MtSi-'>following this link</a>",
            leftList: "",
            rightTitle: "Some notable projects related to this position:",
            rightList: "<li><strong>Main Xiehe Education Organisation website portal</strong> (<a href='https://www.suis.com.cn' target='_blank' rel='noopener noreferrer'>www.suis.com.cn</a>)<br />I have set up, designed, and administered this website based on Drupal until June 2012. It's now unfortunately out of date and lacks the quality I would normally require, but it used to actually look good when I was still in charge of it! </li><li><strong>Moodle installation at Shanghai United International School</strong><br />I have set up the Linux server (Debian), then set up and administered this Moodle website until June 2012. What it looks like now may not reflect my work anymore but I have originally built, set up, administered and maintained it in the past.</li><li><strong>Students Database and Reporting System</strong> (<a href='https://drive.google.com/file/d/0B22ydAZ7kz_NbEZrMHE0UEhCNmM/view' target='_blank' rel='noopener noreferrer'>See a screenshot here</a>)<br />I have helped create and maintain an online, PHP-based administrative database system for storing students information and monitoring other school management matters such as taking attendance, comments, transportation info, reports, etc. I have built the entire reports system from scratch using PHP, HTML and MySQL.</li><li><strong>Portable Netbooks Trolley</strong> (<a href='https://drive.google.com/file/d/0B22ydAZ7kz_NOTg5V3RSeTRJZW8/view' target='_blank' rel='noopener noreferrer'>View document here</a>)<br />Designed a trolley system for Netbooks that is now in use in Shangyin Campus. Click on title above to see the actual plans.</li><li><strong>Set up and maintenance of LAMP servers (Debian), Web services (Apache), Email (postfix+courier), file servers</strong><br />I have set up all the original Linux servers in the school, which ran websites and all the web apps, as well as the original main email system for all the schools based on Postfix and Courier.</li><li><strong>Set up of Access-IT Library Software Platform</strong> (<a href='https://accessitlibrary.com' target='_blank' rel='noopener noreferrer'>https://accessitlibrary.com</a><br />I've performed the installation and set up of the library systems 'Access-IT' on the Linux servers as well as the database</li>"
        },
        {
            id: 6,
            lang: "fr",
            title: "Shanghai United International School",
            subtitle: "2004-2012",
            leftTitle: "Gestionnaire TI inter-campus pour une sérieu d'écoles primaires de Shanghai (Xiehe Education Group). J'ai agi en tant que conseiller, administrateur système, facilitateur TI, et enseignant. Mes tâches incluaient la gestion des infrastructures TI sur tous les campuses, l'administration des serveurs web, bases de données, serveur e-mail, FTP, système de gestion que j'ai en partie développé en PHP, etc. J'ai aussi mis-en-place un système d'enseignement à distance (Moodle) et développé des applis web pour les fonctions administratives (PHP+MySQL). Additionellement, j'ai aussi fourni du support technique et de la formation pour les enseignants, ainsi qu'enseigné les compétences ITC aux étudiants du primaire et secondaire. J'ai suivi le programme du curriculum IB ainsi qu'IPC (auparavant) et le 'English National Curriculum'. Vous pouvez consultez quelques-uns des certificats IB que j'ai acquis en <a href='https://www.dropbox.com/sh/hh6ixhzowx8kle7/EMoi0MtSi-'>suivant ce lien</a>",
            leftList: "",
            rightTitle: "Quelques projets à souligner en lien avec ce poste :",
            rightList: "<li><strong>Site web et portail principal du 'Xiehe Education Organisation'</strong> (<a href='https://www.suis.com.cn' target='_blank' rel='noopener noreferrer'>www.suis.com.cn</a>)<br />J'ai installé, configuré et administré ce site web basé sur Drupal jusqu'en juin 2012. Le site a changé depuis et ne réflète plus mon travail, mais ça a déjà été un excellent site! </li><li><strong>Moodle installation pour Shanghai United International School</strong><br />J'ai installé et configuré le serveur Linux (Debian), puis installé, configuré et administré ce Moodle jusqu'en juin 2012..</li><li><strong>Base de données des étudiants et système de production des bulletins</strong> (<a href='https://drive.google.com/file/d/0B22ydAZ7kz_NbEZrMHE0UEhCNmM/view' target='_blank' rel='noopener noreferrer'>Capture d'écran ici</a>)<br />J'ai contribué à la création de cet outil en ligne, un système basé sur PHP et MySQL pour la gestion de l'information et autres données scolaires telles que: prise des présences, commentaires, information sur les transports, bulletins, etc. J'ai moi-même bâit en entier le système de création des bulletins à l'aide de PHP, HTML and MySQL.</li><li><strong>Chariot de transport pour Netbooks</strong> (<a href='https://drive.google.com/file/d/0B22ydAZ7kz_NOTg5V3RSeTRJZW8/view' target='_blank' rel='noopener noreferrer'>Voir schémas ici</a>)<br />Inventé un système de transport pour Netbooks qui fut construit et utilisé au campus de Shangyin. Cliquez sur le lien pour voir les plans.</li><li><strong>Mise en place et gestion des serveurs LAMP (Debian), services web (Apache), Email (postfix+courier), serveurs de fichiers</strong><br />J'ai mis-en-place tous les serveurs Linux dans l'école, sauvant ainsi des milliers de dollars en licenses logicielles. Ces serveurs ont hébergé tous les sites et applications web, ainsi que le système de courriel pour tous les campus, basé sur Postfix et Courier.</li><li><strong>Configuration du système de bibliothèque Access-IT</strong> (<a href='https://accessitlibrary.com' target='_blank' rel='noopener noreferrer'>https://accessitlibrary.com</a><br />J'ai fait installation et la configuration du système 'Access-IT' sur le serveur Linux ainsi que la base de donnnés</li>"
        }
];

export default ExperienceDb
